//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseAudioPlayer.h"

@interface AMRAudioPlayer : BaseAudioPlayer
{
    _Bool mIsNeedRestartMusic;
}

@property(nonatomic) _Bool needRestartMusic; // @synthesize needRestartMusic=mIsNeedRestartMusic;
- (void)autostop;
- (void)stop;
- (void)replay;
- (void)play;
- (_Bool)preparePlayWithAMRFile:(id)arg1;
- (_Bool)preparePlayNotNotify;
- (void)setDelegate:(id)arg1;
- (void)prepareBuffers;
- (void)setDataFormat;
- (void)openAMRFile:(id)arg1;

@end

