//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BlueProfilePedometer-Protocol.h"

@class BlueDevicePool, NSRecursiveLock, NSString;
@protocol BlueAdapterDelegate, OS_dispatch_queue;

@interface BlueAdapterBase : NSObject <BlueProfilePedometer>
{
    id <BlueAdapterDelegate> m_delegate;
    BlueDevicePool *m_devices;
    NSObject<OS_dispatch_queue> *m_queue;
    NSRecursiveLock *m_lock;
}

@property(retain) NSRecursiveLock *m_lock; // @synthesize m_lock;
@property(nonatomic) __weak id <BlueAdapterDelegate> m_delegate; // @synthesize m_delegate;
@property(retain) BlueDevicePool *m_devices; // @synthesize m_devices;
- (void).cxx_destruct;
- (int)writePedometerProfileTarget:(long long)arg1 Step:(int)arg2;
- (int)readPedometerProfileTarget:(long long)arg1;
- (int)readPedometerProfileCurPedometerInfo:(long long)arg1;
- (int)getProfileConnectState:(long long)arg1;
- (int)getProfileType:(long long)arg1;
- (void)closeProfile:(long long)arg1;
- (int)connectProfile:(long long)arg1 ProfileType:(int)arg2;
- (void)onBlueToothPowerOff;
- (void)writeSession:(long long)arg1:(const char *)arg2:(int)arg3;
- (int)readSession:(long long)arg1:(char *)arg2:(int)arg3;
- (void)closeSession:(long long)arg1;
- (int)connectSession:(long long)arg1;
- (long long)createSession:(long long)arg1;
- (long long)getDIDbySessionID:(long long)arg1;
- (id)getDeviceMac:(long long)arg1;
- (id)getDeviceName:(long long)arg1;
- (id)getDeviceProtocols:(long long)arg1;
- (void)stopScan;
- (_Bool)scanAll;
- (_Bool)scan;
- (void)dealloc;
- (void)cleanUpAllDevices;
- (id)initWithDelegate:(id)arg1 withQueue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

