//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WeixinContentLogicController.h"

#import "BrandDeviceConnectLogicControllerDelegate-Protocol.h"
#import "BrandStyleUILogicControllerDelegate-Protocol.h"
#import "IWCDeviceBrandMgrExt-Protocol.h"
#import "MsgDelegate-Protocol.h"

@class BrandActionReportLogicController, BrandDeviceConnectLogicController, BrandPublicWifiReportLogicController, BrandStyleUILogicController, NSString, TemplateMsgExposeLogic, TipsView;

@interface BrandContentLogicController : WeixinContentLogicController <BrandStyleUILogicControllerDelegate, MsgDelegate, BrandDeviceConnectLogicControllerDelegate, IWCDeviceBrandMgrExt>
{
    TipsView *m_tipsView;
    BrandStyleUILogicController *m_uiLogicController;
    BrandActionReportLogicController *m_reportLogicController;
    BrandDeviceConnectLogicController *m_connectLogicController;
    BrandPublicWifiReportLogicController *m_publicWifiReportLogicController;
    _Bool m_isLastInMenuMode;
    int m_lastInputMode;
    int m_lastPoisitionMode;
    int m_lastContentMode;
    _Bool m_shouldRecordToolViewStatus;
    _Bool m_isShowKeyboardImmediately;
    unsigned long long m_stat_beforeUnread;
    unsigned int m_stat_timeStart;
    TemplateMsgExposeLogic *m_exposeLogic;
}

- (void).cxx_destruct;
- (void)OnTagLink:(id)arg1 messageWrap:(id)arg2;
- (void)onExposeTemplateMsg:(id)arg1;
- (void)addLocalSystemMessageWhenEnterSession;
- (void)hasTapReaderNodeView;
- (void)onTipsViewClick:(id)arg1;
- (_Bool)hasHardDeviceBrandSubtitle;
- (id)GetPossibleContactByName:(id)arg1;
- (void)updateContactFromServer;
- (id)GetTitleTailImage;
- (id)getTitleView:(id)arg1 withSubTitle:(id)arg2;
- (void)onWCDeviceAuthEnd:(int)arg1 DID:(long long)arg2 isHandled:(_Bool *)arg3;
- (_Bool)showKeyboardImmediately;
- (_Bool)shouldHideOrginInputToolView;
- (double)getCustomizedAreaWidth;
- (void)disconnectDevice;
- (void)connectDevice;
- (void)updateToolViewStatus;
- (id)getLogicController;
- (id)getInputToolView;
- (void)recordToolViewStatus;
- (void)showKeyboardImmediatelyEnd;
- (void)showKeyboardImmediatelyStart;
- (void)onModifyCustomMenu:(id)arg1;
- (void)onModifyContact:(id)arg1;
- (void)resetUILogicController:(id)arg1;
- (void)CustomToolViewEX:(id)arg1;
- (void)ViewWillDisappear;
- (void)setNeedUpdateTitle:(_Bool *)arg1;
- (void)ViewDidAppear;
- (void)ViewWillAppear;
- (void)ViewDidInit;
- (void)startScan;
- (void)createAllLogicForContact:(id)arg1;
- (void)ViewWillInit;
- (void)onFinishSelectedLocation;
- (void)hideErrTips;
- (void)showErrTips:(int)arg1;
- (void)updateSubTitle:(id)arg1;
- (void)displayDeviceListView:(id)arg1;
- (_Bool)CanShowSight;
- (_Bool)CanSendVideoMsg;
- (_Bool)CanSendMultiImage;
- (_Bool)CanSendOriginalImage;
- (void)processImageDidFinish;
- (void)processImageDidCancel;
- (void)OnDelMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)OnAddMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)processInsertedAsset:(id)arg1;
- (id)FormImageMsg:(id)arg1 withImage:(id)arg2 withData:(id)arg3;
- (void)OpenDetailInfo;
- (void)OpenContactInfo:(id)arg1;
- (_Bool)isShowHeadImage:(id)arg1;
- (id)GetRightBarButtonImageName;
- (unsigned int)getMsgCountToLoad;
- (_Bool)isShakeEnabled;
- (_Bool)canAutoplayWhenMessageDownloaded;
- (void)HasCustomInputToolViewAndDontNeedShowToolView:(_Bool *)arg1;
- (_Bool)CanSendVoipMsg;
- (_Bool)CanWXTalk;
- (_Bool)CanRemoteRecord;
- (void)onPopFromNavigationController;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

