//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CMultiEvent.h"

@class CUploadImgWrap, NSString;

@interface CGetImgEvent : CMultiEvent
{
    CUploadImgWrap *m_oGetImgWrap;
    NSString *m_nsUsrName;
    unsigned int m_uiLastNotifyPartLen;
    unsigned int m_uiNotifyTotalLen;
    unsigned int m_uiLastNotifyPercent;
}

@property(retain, nonatomic) NSString *m_nsUsrName; // @synthesize m_nsUsrName;
- (void).cxx_destruct;
- (void)NotifyFromEvent:(id)arg1 Message:(unsigned int)arg2 MessageInfo:(id)arg3;
- (void)TimerCheckEvent;
- (void)SetNotifyData:(unsigned int)arg1 PartLen:(unsigned int)arg2 Complete:(_Bool)arg3;
- (_Bool)HandleGetImgPart:(id)arg1;
- (_Bool)CreateImplGetImg;
- (void)NotifyError:(unsigned int)arg1 MessageInfo:(id)arg2;
- (void)Stop;
- (_Bool)Start:(unsigned int *)arg1 RetInfo:(id)arg2;
- (_Bool)SetEventInfo:(id)arg1;
- (void)dealloc;
- (id)init;

@end

