//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSyncBaseEvent.h"

@class NSData, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface CImplNewInitEvent : CSyncBaseEvent
{
    NSString *m_nsUsrName;
    NSData *m_dtCurSyncBuffer;
    NSData *m_dtMaxSyncBuffer;
    unsigned int m_uiScene;
    NSObject<OS_dispatch_queue> *m_worker;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *m_worker; // @synthesize m_worker;
@property(retain, nonatomic) NSData *m_dtMaxSyncBuffer; // @synthesize m_dtMaxSyncBuffer;
@property(retain, nonatomic) NSData *m_dtCurSyncBuffer; // @synthesize m_dtCurSyncBuffer;
@property(retain, nonatomic) NSString *m_nsUsrName; // @synthesize m_nsUsrName;
- (void).cxx_destruct;
- (_Bool)Start:(unsigned int *)arg1 RetInfo:(id)arg2;
- (_Bool)SetEventInfo:(id)arg1;
- (void)dealloc;
- (id)init;

@end

