//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class BaseRequest, NSMutableArray, NSString;

@interface ClickCommandRequest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;
@property(retain, nonatomic) NSString *bizUserName; // @dynamic bizUserName;
@property(retain, nonatomic) NSString *clickInfo; // @dynamic clickInfo;
@property(nonatomic) unsigned int clickType; // @dynamic clickType;
@property(retain, nonatomic) NSMutableArray *msgReport; // @dynamic msgReport;
@property(retain, nonatomic) NSString *msgSource; // @dynamic msgSource;

@end

