//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface ColorGradientView : UIView
{
}

- (void)commonConfiWithColor:(id)arg1 alphaTop:(double)arg2 alphaBottom:(double)arg3;
- (unsigned long long)countOfSubLayers;
- (void)configureWithColor:(id)arg1 alphaTop:(double)arg2 alphaBottom:(double)arg3;
- (id)initWithFrame:(struct CGRect)arg1 color:(id)arg2 alphaTop:(double)arg3 alphaBottom:(double)arg4;

@end

