//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CSVoipMemberInfo : NSObject
{
    unsigned int memberid;
    unsigned int status;
    unsigned int substatus;
    unsigned int seq;
}

@property(nonatomic) unsigned int seq; // @synthesize seq;
@property(nonatomic) unsigned int substatus; // @synthesize substatus;
@property(nonatomic) unsigned int status; // @synthesize status;
@property(nonatomic) unsigned int memberid; // @synthesize memberid;

@end

