//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface DeviceFollowItem : MMObject <PBCoding>
{
    unsigned int uiStep;
    unsigned int uiIndex;
    NSString *nsUserName;
}

+ (void)initialize;
@property(nonatomic) unsigned int uiIndex; // @synthesize uiIndex;
@property(nonatomic) unsigned int uiStep; // @synthesize uiStep;
@property(copy, nonatomic) NSString *nsUserName; // @synthesize nsUserName;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

