//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class DisturbTimeSpan;

@interface DisturbSetting : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int allDaySetting; // @dynamic allDaySetting;
@property(retain, nonatomic) DisturbTimeSpan *allDayTime; // @dynamic allDayTime;
@property(nonatomic) unsigned int nightSetting; // @dynamic nightSetting;
@property(retain, nonatomic) DisturbTimeSpan *nightTime; // @dynamic nightTime;

@end

