//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EditVideoAttr, NSString, UIImage;

@protocol EditVideoInitialViewDelegate <NSObject>
- (_Bool)isExceedTimelineTimeLimit;
- (float)getOutputTime;
- (NSString *)getAssetUrl;
- (UIImage *)getThumbImage;
- (struct CGSize)getImageRatioSize;
- (EditVideoAttr *)getVideoAttr;
- (CDStruct_e83c9415)getEditedVideoTimeRange;
- (void)onClickEditVideoDoneButton;
- (void)onClickEditVideoCancelButton;
- (void)onCropTimeChange:(CDStruct_e83c9415)arg1;
- (void)onSeekTime:(double)arg1;
- (void)onCropCancel;
- (void)onCropDone:(CDStruct_e83c9415)arg1;
@end

