//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBCoding-Protocol.h"

@class NSMutableArray, NSString;

@interface EmoticonStoreListCache : MMObject <PBCoding>
{
    unsigned int m_topHotNum;
    unsigned int m_recentHotNum;
    NSMutableArray *itemList;
    NSMutableArray *m_adArray;
    NSMutableArray *m_cellSetList;
}

+ (void)initialize;
@property(retain, nonatomic) NSMutableArray *m_cellSetList; // @synthesize m_cellSetList;
@property(retain, nonatomic) NSMutableArray *m_adArray; // @synthesize m_adArray;
@property(nonatomic) unsigned int m_recentHotNum; // @synthesize m_recentHotNum;
@property(nonatomic) unsigned int m_topHotNum; // @synthesize m_topHotNum;
@property(retain, nonatomic) NSMutableArray *itemList; // @synthesize itemList;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

