//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface EmoticonStoreReportInfo : NSObject
{
    unsigned long long _searchId;
    unsigned long long _docId;
}

@property(nonatomic) unsigned long long docId; // @synthesize docId=_docId;
@property(nonatomic) unsigned long long searchId; // @synthesize searchId=_searchId;

@end

