//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FaceRecogBaseViewController.h"

#import "FaceRecogGuideViewControllerDelegate-Protocol.h"
#import "FaceRecogNumbersViewDelegate-Protocol.h"
#import "FaceRecogRectViewDelegate-Protocol.h"

@class AnimationStatusView, FaceRecogGuideViewController, FaceRecogNumbersView, FaceRecogRectView, MMUILabel, NSString, UIButton, UIImageView, UIView;
@protocol FaceRecogVerifyViewControllerDelegate;

@interface FaceRecogVerifyViewController : FaceRecogBaseViewController <FaceRecogNumbersViewDelegate, FaceRecogGuideViewControllerDelegate, FaceRecogRectViewDelegate>
{
    UIView *_prepareView;
    AnimationStatusView *_waitView;
    UIImageView *_faceIcon;
    UIView *_previewView;
    UIButton *_cancelButton;
    UIButton *_closeButton;
    UIButton *_retryButton;
    FaceRecogRectView *_faceRectView;
    UIView *_faceRectBackView;
    UIView *_faceGradientView;
    FaceRecogNumbersView *_numberView;
    MMUILabel *_bigTipFaceTitle;
    MMUILabel *_errTip;
    UIImageView *_loadingBlurView;
    _Bool _finished;
    FaceRecogGuideViewController *_guideVc;
    UIView *_numberContainerView;
    UIButton *_startBtn;
    MMUILabel *_prepareReadNumTitleLabel;
    _Bool _bNeedGuide;
    id <FaceRecogVerifyViewControllerDelegate> _delegate;
}

@property(nonatomic) _Bool bNeedGuide; // @synthesize bNeedGuide=_bNeedGuide;
@property(nonatomic) __weak id <FaceRecogVerifyViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didTapStartReadNumberBtn;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)numberViewDidEndAnimation;
- (void)numberViewDidBeginAnimation;
- (void)onFaceRecogGuideFinished;
- (void)onFaceRecogGuideCanceled;
- (void)retryButtonDone;
- (void)closeButtonDone;
- (void)cancelButtonDone;
- (void)initNumberContainerView;
- (void)catchedFaceDidEndAnimation;
- (void)procedureDidShowPrepareReadNumberTips;
- (void)procedureDidFailed:(id)arg1 canRetry:(_Bool)arg2;
- (void)procedureDidFinish;
- (void)procedureDidStartRecogning;
- (void)showPrepareView;
- (void)procedureDidStartReadNumber:(id)arg1 Time:(double)arg2;
- (void)procedureDidStartDetectFace;
- (void)procedureDidGotFrameResult:(id)arg1 currentMotionType:(unsigned long long)arg2 failedType:(long long)arg3;
- (void)attachPreviewLayer:(id)arg1;
- (void)initCancelBtn;
- (void)initNumberView;
- (void)initFaceRectView;
- (void)initPrepareView:(id)arg1 tip:(id)arg2;
- (void)initErrorMsg:(id)arg1;
- (void)initBitTipTitle:(id)arg1;
- (void)initView;
- (void)resetViews;
- (_Bool)isReadyToReadNumber;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

