//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class NSString;

@interface FacingMember : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *encodeUserName; // @dynamic encodeUserName;
@property(retain, nonatomic) NSString *nickName; // @dynamic nickName;
@property(retain, nonatomic) NSString *smallImgUrl; // @dynamic smallImgUrl;
@property(nonatomic) unsigned int status; // @dynamic status;
@property(retain, nonatomic) NSString *userName; // @dynamic userName;

@end

