//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class NSString;

@interface FavCDNItem : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *aeskey; // @dynamic aeskey;
@property(retain, nonatomic) NSString *cdnurl; // @dynamic cdnurl;
@property(retain, nonatomic) NSString *dataId; // @dynamic dataId;
@property(nonatomic) int dataStatus; // @dynamic dataStatus;
@property(nonatomic) int encryVer; // @dynamic encryVer;
@property(retain, nonatomic) NSString *fullMd5; // @dynamic fullMd5;
@property(nonatomic) unsigned int fullSize; // @dynamic fullSize;
@property(retain, nonatomic) NSString *head256Md5; // @dynamic head256Md5;
@property(nonatomic) int status; // @dynamic status;
@property(retain, nonatomic) NSString *videoId; // @dynamic videoId;

@end

