//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface FICEntityMetadata : NSObject <PBCoding>
{
    _Bool _hasImageCache;
    unsigned int entityIndex;
    unsigned int eliminationFactor;
    unsigned int LRUFactor;
    unsigned int _entityUsedCount;
    NSString *_entityUUID;
}

+ (void)initialize;
@property(nonatomic) _Bool hasImageCache; // @synthesize hasImageCache=_hasImageCache;
@property(nonatomic) unsigned int entityUsedCount; // @synthesize entityUsedCount=_entityUsedCount;
@property(retain, nonatomic) NSString *entityUUID; // @synthesize entityUUID=_entityUUID;
@property(nonatomic) unsigned int LRUFactor; // @synthesize LRUFactor;
@property(nonatomic) unsigned int eliminationFactor; // @synthesize eliminationFactor;
@property(nonatomic) unsigned int entityIndex; // @synthesize entityIndex;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

