//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class MMUILabel, UIImageView;

@interface FTSCreateChatRoomCell : MMTableViewCell
{
    UIImageView *_imageView;
    MMUILabel *_intentLabel;
    MMUILabel *_descLabel;
}

- (void).cxx_destruct;
- (void)updateCellWithKeywords:(id)arg1;
- (void)initView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

