//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class MMUILabel, UIImageView;

@interface FTSMsgSearchTalkerCell : MMTableViewCell
{
    UIImageView *_magnifier;
    MMUILabel *_titleLabel;
}

- (void).cxx_destruct;
- (void)updateTalker:(id)arg1 andQuery:(id)arg2 withInSession:(_Bool)arg3;
- (id)compressString:(id)arg1 contraintWidth:(double)arg2;
- (void)initView;
- (id)init;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

