//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBMessageObserverDelegate-Protocol.h"

@protocol GameSearchManagerDelegate;

@interface GameSearchManager : NSObject <PBMessageObserverDelegate>
{
    unsigned int _eventID;
    id <GameSearchManagerDelegate> _delegate;
}

@property(nonatomic) unsigned int eventID; // @synthesize eventID=_eventID;
@property(nonatomic) __weak id <GameSearchManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)handleSearchResponse:(id)arg1 Event:(unsigned int)arg2;
- (void)didFinishWithResultGroups:(id)arg1 searchWithText:(id)arg2 error:(long long)arg3;
- (_Bool)sendSearchRequestWithKeywords:(id)arg1 searchWithText:(id)arg2;
- (_Bool)requestSearchWithText:(id)arg1;

@end

