//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class BaseResponse, NSString, OpenAppInfo;

@interface GetAppInfoResponse : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) OpenAppInfo *appInfo; // @dynamic appInfo;
@property(retain, nonatomic) NSString *appType; // @dynamic appType;
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) NSString *devInfo; // @dynamic devInfo;
@property(nonatomic) unsigned int noUse; // @dynamic noUse;

@end

