//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSObject, NSString;

@protocol IMMQuartz2DContextDelegate <NSObject>
- (double)getMiterLimit;
- (void)setMiterLimit:(double)arg1;
- (int)getLineJoin;
- (void)setLineJoin:(int)arg1;
- (int)getLineCap;
- (void)setLineCap:(int)arg1;
- (double)getLineWidth;
- (void)setLineWidth:(double)arg1;
- (void)resetGradient;
- (NSArray *)getGradient;
- (void)setGradient:(NSArray *)arg1;
- (double)getContextHeght;
- (void)restoreContext:(struct CGContext *)arg1;
- (void)saveContext:(struct CGContext *)arg1;
- (void)setTranslate:(double)arg1 translateY:(double)arg2;
- (void)setRotate:(double)arg1;
- (void)setScale:(double)arg1 scaleY:(double)arg2;
- (void)setContext:(NSObject *)arg1 forKey:(NSString *)arg2;
- (NSObject *)getContext:(NSString *)arg1;
@end

