//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

@class NSString;

@interface InviteSourceInfo : MMObject
{
    unsigned int _sourceTag;
    NSString *_sourceName;
    NSString *_sourceIconName;
    SEL _sourceActionSel;
}

@property(nonatomic) SEL sourceActionSel; // @synthesize sourceActionSel=_sourceActionSel;
@property(copy, nonatomic) NSString *sourceIconName; // @synthesize sourceIconName=_sourceIconName;
@property(copy, nonatomic) NSString *sourceName; // @synthesize sourceName=_sourceName;
@property(nonatomic) unsigned int sourceTag; // @synthesize sourceTag=_sourceTag;
- (void).cxx_destruct;

@end

