//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CMessageWrap;

@protocol ISightExt
- (void)UpdateSightVideoDownloadMsg:(CMessageWrap *)arg1;
- (void)OnSightThumbDidChange:(CMessageWrap *)arg1;
- (void)OnSightThumbDownloadFailed:(CMessageWrap *)arg1;
- (void)OnSightThumbDownloadOK:(CMessageWrap *)arg1;
@end

