//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class NSString;

@interface Log_PBTest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *aid; // @dynamic aid;
@property(nonatomic) int clientVersion; // @dynamic clientVersion;
@property(nonatomic) int device; // @dynamic device;
@property(nonatomic) int ds; // @dynamic ds;
@property(nonatomic) int f; // @dynamic f;
@property(nonatomic) int ff; // @dynamic ff;
@property(nonatomic) int importDs; // @dynamic importDs;
@property(nonatomic) int ps; // @dynamic ps;
@property(retain, nonatomic) NSString *sid; // @dynamic sid;
@property(nonatomic) long long timeStamp; // @dynamic timeStamp;
@property(nonatomic) int tsf; // @dynamic tsf;
@property(nonatomic) long long uin; // @dynamic uin;
@property(retain, nonatomic) NSString *wifi; // @dynamic wifi;

@end

