//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class VoiceInputBehavior;

@interface log_13905 : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) int clientVersion; // @dynamic clientVersion;
@property(nonatomic) int device; // @dynamic device;
@property(nonatomic) int ds; // @dynamic ds;
@property(nonatomic) int importDs; // @dynamic importDs;
@property(nonatomic) long long timeStamp; // @dynamic timeStamp;
@property(nonatomic) long long uin; // @dynamic uin;
@property(retain, nonatomic) VoiceInputBehavior *viOp; // @dynamic viOp;

@end

