//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class NSString;

@interface LoginDevice : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *devicename; // @dynamic devicename;
@property(retain, nonatomic) NSString *devicetype; // @dynamic devicetype;
@property(nonatomic) unsigned int lasttime; // @dynamic lasttime;
@property(retain, nonatomic) NSString *uuid; // @dynamic uuid;

@end

