//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate;

@interface lzCacheCleanManager : NSObject
{
    NSDate *_lastCleanDate;
}

- (void).cxx_destruct;
- (_Bool)isExpFile:(id)arg1;
- (id)scanCachePath:(id)arg1;
- (_Bool)isFileCaching:(id)arg1 cacheMgr:(id)arg2;
- (void)removeFiles:(id)arg1 cacheMgr:(id)arg2;
- (void)cleanCache:(id)arg1 filterBlock:(CDUnknownBlockType)arg2 queue:(id)arg3;
- (void)dealloc;
- (id)init;

@end

