//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBMessageObserverDelegate-Protocol.h"

@class NSMutableDictionary;
@protocol HeadImgDownloaderDelegate;

@interface MMHDHeadImgDownloader : MMObject <PBMessageObserverDelegate>
{
    id <HeadImgDownloaderDelegate> downloadDelegate;
    NSMutableDictionary *_m_downloadTaskDic;
}

@property(retain, nonatomic) NSMutableDictionary *m_downloadTaskDic; // @synthesize m_downloadTaskDic=_m_downloadTaskDic;
@property(nonatomic) __weak id <HeadImgDownloaderDelegate> downloadDelegate; // @synthesize downloadDelegate;
- (void).cxx_destruct;
- (void)onDownloadPartOK:(id)arg1 task:(id)arg2;
- (void)onDownloadPartFailForTask:(id)arg1;
- (void)ondownloadCompleteForTask:(id)arg1;
- (void)updateNormalHeadForTask:(id)arg1;
- (id)generateNormalHeadData:(id)arg1;
- (void)MessageReturnCDN:(id)arg1 task:(id)arg2;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (unsigned int)downloadHDHeadImg:(id)arg1 url:(id)arg2 forCategory:(unsigned char)arg3;
- (unsigned int)downloadHDHeadImg:(id)arg1 forCategory:(unsigned char)arg2;
- (void)stopDownloadForName:(id)arg1;
- (_Bool)saveData:(id)arg1 forTask:(id)arg2 file:(id)arg3;
- (_Bool)downloadHDImg:(id)arg1 offset:(unsigned int)arg2 len:(unsigned int)arg3;
- (unsigned int)getFileSize:(id)arg1;
- (id)getTempFilePath:(id)arg1;
- (void)removeTaskForName:(id)arg1;
- (id)getTaskForName:(id)arg1;
- (_Bool)addTask:(id)arg1;
- (_Bool)isExistTheSameUsername:(id)arg1;
- (void)dealloc;
- (id)init;

@end

