//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPageControl.h>

@class UIImage;

@interface MMPageControl : UIPageControl
{
    UIImage *_activeImage;
    UIImage *_inactiveImage;
}

@property(retain, nonatomic) UIImage *inactiveImage; // @synthesize inactiveImage=_inactiveImage;
@property(retain, nonatomic) UIImage *activeImage; // @synthesize activeImage=_activeImage;
- (void).cxx_destruct;
- (void)setCurrentPage:(long long)arg1;
- (void)updateDots;

@end

