//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MMWebImageView, UIImageView, UILabel, UIView;

@interface MMStoreEmotionStoreListCell : UICollectionViewCell
{
    MMWebImageView *_m_webImageView;
    MMWebImageView *_m_tagImageView;
    UIImageView *_m_newImageView;
    UIImageView *_m_rightArrowImage;
    UILabel *_m_nameLabel;
    UILabel *_m_introduceLabel;
    UIView *_m_lineView;
}

@property(retain, nonatomic) UIView *m_lineView; // @synthesize m_lineView=_m_lineView;
@property(retain, nonatomic) UILabel *m_introduceLabel; // @synthesize m_introduceLabel=_m_introduceLabel;
@property(retain, nonatomic) UILabel *m_nameLabel; // @synthesize m_nameLabel=_m_nameLabel;
@property(retain, nonatomic) UIImageView *m_rightArrowImage; // @synthesize m_rightArrowImage=_m_rightArrowImage;
@property(retain, nonatomic) UIImageView *m_newImageView; // @synthesize m_newImageView=_m_newImageView;
@property(retain, nonatomic) MMWebImageView *m_tagImageView; // @synthesize m_tagImageView=_m_tagImageView;
@property(retain, nonatomic) MMWebImageView *m_webImageView; // @synthesize m_webImageView=_m_webImageView;
- (void).cxx_destruct;
- (void)adjustLabelsWidthWithRightViewX:(double)arg1;
- (void)setIntroduceLabelText:(id)arg1;
- (void)setNameLabelText:(id)arg1;
- (void)configRightArrowImage;
- (void)loadTagImageView;
- (void)initIntroduceLabel;
- (void)initNameLabel;
- (void)initWebImageView;
- (void)initLineView;
- (void)setHighlighted:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

