//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface MultiTalkGroupMemberItem : MMObject <PBCoding>
{
    int status;
    int reason;
    int holdStatus;
    NSString *userName;
    NSString *inviteUserName;
    long long inviteTime;
}

+ (void)initialize;
@property(nonatomic) int holdStatus; // @synthesize holdStatus;
@property(nonatomic) long long inviteTime; // @synthesize inviteTime;
@property(nonatomic) int reason; // @synthesize reason;
@property(nonatomic) int status; // @synthesize status;
@property(retain, nonatomic) NSString *inviteUserName; // @synthesize inviteUserName;
@property(retain, nonatomic) NSString *userName; // @synthesize userName;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

