//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (Swizzle)
+ (void)swizzleRemoveObjectForKey:(Class)arg1;
+ (void)swizzleSetObjectForKeyedSubscript:(Class)arg1;
+ (void)swizzleSetObjectForKey:(Class)arg1;
+ (void)swizzleInitWithObjectsForKeysCount:(Class)arg1;
+ (void)swizzleObjectForKeyedSubscript:(Class)arg1;
+ (void)swizzleInitWithObjectsForKeys:(Class)arg1;
+ (void)load;
@end

