//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSSimplifiedChineseConverter : NSObject
{
    map_c52e7b28 _t2sMap;
}

+ (id)sharedInstance;
@property(nonatomic) map_c52e7b28 t2sMap; // @synthesize t2sMap=_t2sMap;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)loadMap;
- (id)simplify:(id)arg1;

@end

