//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSStringHelper : NSObject
{
}

+ (_Bool)ISMcID:(id)arg1;
+ (_Bool)ISTwID:(id)arg1;
+ (_Bool)ISHkID:(id)arg1;
+ (_Bool)isTaiBaoID:(id)arg1;
+ (_Bool)isHuiXiangID:(id)arg1;
+ (_Bool)invalidateID:(id)arg1;
+ (_Bool)isUserIDNum:(id)arg1;
+ (_Bool)isBankCardNum:(id)arg1;
+ (_Bool)isPhoneNum:(id)arg1;
+ (_Bool)isDigit:(id)arg1 Length:(unsigned long long)arg2;

@end

