//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QBBeaconEncodeObject.h"

#import "QBBeaconPersistEncoding-Protocol.h"

@class NSString;

@interface QBBeaconPersistObject : QBBeaconEncodeObject <QBBeaconPersistEncoding>
{
    long long dbid;
    long long encLength;
    long long md5;
    long long time;
    int priority;
    int type;
    int dcount;
}

@property(nonatomic) long long md5; // @synthesize md5;
@property(nonatomic) int dcount; // @synthesize dcount;
@property(nonatomic) int type; // @synthesize type;
@property(nonatomic) long long time; // @synthesize time;
@property(nonatomic) int priority; // @synthesize priority;
@property(nonatomic) long long encLength; // @synthesize encLength;
@property(nonatomic) long long dbid; // @synthesize dbid;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

