//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QBRequestPacket.h"

@class QBUniAttribute;

@interface QBUniPacket : QBRequestPacket
{
    QBUniAttribute *_attributes;
}

+ (id)packet;
@property(readonly, nonatomic) QBUniAttribute *attributes; // @synthesize attributes=_attributes;
- (void).cxx_destruct;
- (long long)getReturnCode;
- (void)putObjectAttr:(id)arg1 value:(id)arg2;
- (void)putObjectAttr:(id)arg1 type:(id)arg2 value:(id)arg3;
- (void)putDataAttr:(id)arg1 value:(id)arg2;
- (id)getObjectAttr:(id)arg1 forClass:(Class)arg2;
- (void)__unpack:(id)arg1;
- (void)__pack:(id)arg1;
- (id)objectKeyWithName:(id)arg1;
- (id)description;
- (id)init;

@end

