//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class BaseResponse, NSString, RcptInfoList;

@interface RcptInfoQueryResponse : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *appnickname; // @dynamic appnickname;
@property(retain, nonatomic) NSString *appusername; // @dynamic appusername;
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(nonatomic) unsigned int isauthority; // @dynamic isauthority;
@property(nonatomic) unsigned int islatest; // @dynamic islatest;
@property(retain, nonatomic) RcptInfoList *rcptinfolist; // @dynamic rcptinfolist;

@end

