//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "MMKernelExt-Protocol.h"
#import "MMService-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class NSString;

@interface ReportStrategyCtrlMgr : MMService <PBMessageObserverDelegate, MMService, MMKernelExt>
{
}

- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)HandleReportStrategyResp:(id)arg1 Event:(unsigned int)arg2;
- (void)SendReportStrategyRequest;
- (void)dealloc;
- (id)init;
- (void)onAuthOK;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

