//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

@class NSDictionary, NSRecursiveLock;

@interface SafeDictionaryWrap : MMObject
{
    NSRecursiveLock *_lock;
    NSDictionary *_dic;
}

- (void).cxx_destruct;
- (unsigned long long)count;
- (id)objectForKey:(id)arg1;
- (void)safeSetDictionrary:(id)arg1;
- (id)init;

@end

