//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "PBCoding-Protocol.h"

@class NSString, SubscriptBrandInfo;

@interface ShakePeopleItem : NSObject <PBCoding, NSCoding>
{
    NSString *m_nsUserName;
    NSString *m_nsNickName;
    NSString *m_nsCountry;
    NSString *m_nsProvince;
    NSString *m_nsCity;
    unsigned int m_uiSex;
    NSString *m_nsDistance;
    NSString *m_nsSignature;
    unsigned int m_uiScene;
    NSString *m_nsWeiboAddress;
    NSString *m_nsWeiboNickName;
    unsigned int m_uiWeiboFlag;
    unsigned int m_uiVerifyFlag;
    NSString *m_nsVerifyInfo;
    NSString *m_nsVerifyContent;
    NSString *m_nsWCBGImgObjectID;
    int m_iAlbumFlag;
    NSString *m_pcAlbumBGImgID;
    NSString *m_nsExternalInfo;
    NSString *m_nsBrandSubscriptConfigUrl;
    unsigned int m_uiBrandSubscriptionSettings;
    SubscriptBrandInfo *m_subBrandInfo;
    NSString *m_nsBrandIconUrl;
    unsigned int m_createTime;
    NSString *m_headImgUrl;
    NSString *m_nsHeadHDImgUrl;
    NSString *m_nsAntispamTicket;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *m_nsAntispamTicket; // @synthesize m_nsAntispamTicket;
@property(retain, nonatomic) NSString *m_nsHeadHDImgUrl; // @synthesize m_nsHeadHDImgUrl;
@property(retain, nonatomic) NSString *m_headImgUrl; // @synthesize m_headImgUrl;
@property(nonatomic) unsigned int m_createTime; // @synthesize m_createTime;
@property(retain, nonatomic) NSString *m_nsBrandIconUrl; // @synthesize m_nsBrandIconUrl;
@property(retain, nonatomic) SubscriptBrandInfo *m_subBrandInfo; // @synthesize m_subBrandInfo;
@property(nonatomic) unsigned int m_uiBrandSubscriptionSettings; // @synthesize m_uiBrandSubscriptionSettings;
@property(retain, nonatomic) NSString *m_nsBrandSubscriptConfigUrl; // @synthesize m_nsBrandSubscriptConfigUrl;
@property(retain, nonatomic) NSString *m_nsExternalInfo; // @synthesize m_nsExternalInfo;
@property(retain, nonatomic) NSString *m_pcAlbumBGImgID; // @synthesize m_pcAlbumBGImgID;
@property(nonatomic) int m_iAlbumFlag; // @synthesize m_iAlbumFlag;
@property(retain, nonatomic) NSString *m_nsWCBGImgObjectID; // @synthesize m_nsWCBGImgObjectID;
@property(retain, nonatomic) NSString *m_nsVerifyContent; // @synthesize m_nsVerifyContent;
@property(retain, nonatomic) NSString *m_nsVerifyInfo; // @synthesize m_nsVerifyInfo;
@property(nonatomic) unsigned int m_uiVerifyFlag; // @synthesize m_uiVerifyFlag;
@property(nonatomic) unsigned int m_uiWeiboFlag; // @synthesize m_uiWeiboFlag;
@property(retain, nonatomic) NSString *m_nsWeiboNickName; // @synthesize m_nsWeiboNickName;
@property(retain, nonatomic) NSString *m_nsWeiboAddress; // @synthesize m_nsWeiboAddress;
@property(nonatomic) unsigned int m_uiScene; // @synthesize m_uiScene;
@property(retain, nonatomic) NSString *m_nsSignature; // @synthesize m_nsSignature;
@property(retain, nonatomic) NSString *m_nsDistance; // @synthesize m_nsDistance;
@property(nonatomic) unsigned int m_uiSex; // @synthesize m_uiSex;
@property(retain, nonatomic) NSString *m_nsCity; // @synthesize m_nsCity;
@property(retain, nonatomic) NSString *m_nsProvince; // @synthesize m_nsProvince;
@property(retain, nonatomic) NSString *m_nsCountry; // @synthesize m_nsCountry;
@property(retain, nonatomic) NSString *m_nsNickName; // @synthesize m_nsNickName;
@property(retain, nonatomic) NSString *m_nsUserName; // @synthesize m_nsUserName;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)init;
- (void)preInit;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

