//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "MMService-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class NSString, ShakeInfo;

@interface ShakeBgImgDownloadMgr : MMService <MMService, PBMessageObserverDelegate>
{
    ShakeInfo *m_oShakeInfo;
    unsigned int m_uiCurDownloadID;
    unsigned int m_uiCurTotalLen;
    unsigned int m_uiCurEventID;
    unsigned int m_uiCurDownloadCount;
}

@property(retain, nonatomic) ShakeInfo *m_oShakeInfo; // @synthesize m_oShakeInfo;
- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)DownloadBgImg:(unsigned int)arg1 TotalLen:(unsigned int)arg2;
- (void)CreateDownloadEvent;
- (void)AddShakeTimes:(unsigned int)arg1;
- (unsigned int)GetShakeBgImgID;
- (unsigned int)GetShakeTimes;
- (void)SaveShakeInfo;
- (void)LoadShakeInfo;
- (void)dealloc;
- (id)init;
- (void)ResetDownloadInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

