//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class NSMutableArray;

@interface ShareTag : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *shareUins; // @dynamic shareUins;
@property(retain, nonatomic) NSMutableArray *shareUser; // @dynamic shareUser;
@property(retain, nonatomic) NSMutableArray *unshareUins; // @dynamic unshareUins;
@property(retain, nonatomic) NSMutableArray *unshareUser; // @dynamic unshareUser;

@end

