//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class NSString;

@interface SnsWeAppInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int appId; // @dynamic appId;
@property(retain, nonatomic) NSString *mapPoiId; // @dynamic mapPoiId;
@property(retain, nonatomic) NSString *redirectUrl; // @dynamic redirectUrl;
@property(nonatomic) unsigned int score; // @dynamic score;
@property(nonatomic) unsigned int showType; // @dynamic showType;
@property(retain, nonatomic) NSString *userName; // @dynamic userName;

@end

