//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TBSReadWriteLock : NSObject
{
    struct _opaque_pthread_rwlock_t {
        long long __sig;
        char __opaque[192];
    } rwlock;
}

- (void)dealloc;
- (id)init;
- (int)TBS_Unlock;
- (int)TBS_ReaderLock;
- (int)TBS_WriterLock;

@end

