//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ICdnComMgrExt-Protocol.h"

@class CdnTaskInfo, NSMutableArray, NSString;
@protocol OS_dispatch_queue;

@interface ThumbDownloadMgr : NSObject <ICdnComMgrExt>
{
    NSMutableArray *m_arrQueue;
    CdnTaskInfo *m_oCurTaskInfo;
    NSObject<OS_dispatch_queue> *m_thumbDownloadQueue;
}

@property(retain, nonatomic) CdnTaskInfo *m_oCurTaskInfo; // @synthesize m_oCurTaskInfo;
- (void).cxx_destruct;
- (void)OnCdnDownload:(id)arg1;
- (void)OnSetCdnDnsInfo;
- (void)DownloadFail:(int)arg1;
- (void)StopDownloadThumbByUsrName:(id)arg1;
- (void)StopDownloadThumb:(id)arg1;
- (void)StopCurDownload;
- (_Bool)StartDownloadThumb:(id)arg1;
- (_Bool)IsDownloadingThumb:(id)arg1;
- (void)CheckQueue;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

