//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDictionary, NSString;

@interface TXCPlayerConfig : NSObject <NSCopying>
{
    _Bool _enableNearestIP;
    _Bool _enableHWAcceleration;
    _Bool _autoAdjustCache;
    int _rtmpChannelType;
    float _cacheTime;
    float _minAutoAdjustCacheTime;
    float _maxAutoAdjustCacheTime;
    int _maxCacheItems;
    int _playerPixelFormatType;
    long long _downloadFormat;
    long long _rotation;
    long long _renderMode;
    long long _reconnectLimit;
    double _reconnectInterval;
    double _vodTimeout;
    NSString *_cacheFolderPath;
    NSDictionary *_headers;
}

@property(retain) NSDictionary *headers; // @synthesize headers=_headers;
@property int playerPixelFormatType; // @synthesize playerPixelFormatType=_playerPixelFormatType;
@property int maxCacheItems; // @synthesize maxCacheItems=_maxCacheItems;
@property(retain) NSString *cacheFolderPath; // @synthesize cacheFolderPath=_cacheFolderPath;
@property(nonatomic) double vodTimeout; // @synthesize vodTimeout=_vodTimeout;
@property(nonatomic) double reconnectInterval; // @synthesize reconnectInterval=_reconnectInterval;
@property(nonatomic) long long reconnectLimit; // @synthesize reconnectLimit=_reconnectLimit;
@property(nonatomic) float maxAutoAdjustCacheTime; // @synthesize maxAutoAdjustCacheTime=_maxAutoAdjustCacheTime;
@property(nonatomic) float minAutoAdjustCacheTime; // @synthesize minAutoAdjustCacheTime=_minAutoAdjustCacheTime;
@property(nonatomic) float cacheTime; // @synthesize cacheTime=_cacheTime;
@property(nonatomic) _Bool autoAdjustCache; // @synthesize autoAdjustCache=_autoAdjustCache;
@property(nonatomic) long long renderMode; // @synthesize renderMode=_renderMode;
@property(nonatomic) long long rotation; // @synthesize rotation=_rotation;
@property(nonatomic) _Bool enableHWAcceleration; // @synthesize enableHWAcceleration=_enableHWAcceleration;
@property(nonatomic) int rtmpChannelType; // @synthesize rtmpChannelType=_rtmpChannelType;
@property(nonatomic) _Bool enableNearestIP; // @synthesize enableNearestIP=_enableNearestIP;
@property(nonatomic) long long downloadFormat; // @synthesize downloadFormat=_downloadFormat;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

