//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_source, TXINotifyDelegate, TXIQoSDelegate;

@interface TXCQoS : NSObject
{
    struct TXCQoSCore *_qos;
    NSObject<OS_dispatch_source> *_timer;
    _Bool _isEnableDrop;
    long long _bitrate;
    long long _width;
    long long _height;
    double _interval;
    _Bool _isWorking;
    id <TXIQoSDelegate> _delegate;
    id <TXINotifyDelegate> _notifyDelegate;
}

+ (long long)getProperResolutionByVideoBitrate:(_Bool)arg1 videoAspect:(long long)arg2 videoBitrate:(long long)arg3;
@property(nonatomic) id <TXINotifyDelegate> notifyDelegate; // @synthesize notifyDelegate=_notifyDelegate;
@property(nonatomic) id <TXIQoSDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setVideoExpectBitrate:(long long)arg1;
- (void)setVideoEncBitrateMin:(long long)arg1 max:(long long)arg2 def:(long long)arg3;
- (void)setDefaultVideoResolution:(long long)arg1;
- (void)setAutoAdjustStrategy:(long long)arg1;
- (void)setEnableAutoBitrate:(_Bool)arg1;
- (void)setHasVideo:(_Bool)arg1;
- (_Bool)isEnableDrop;
- (void)resetWithAutoBitrate:(_Bool)arg1;
- (void)doQos;
- (void)stop;
- (void)startWithInterval:(double)arg1;
- (void)dealloc;
- (id)initWithAutoBitrate:(_Bool)arg1;

@end

