//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface TXSAudioPacket : NSObject
{
    long long _sampleRate;
    long long _channelsPerSample;
    long long _bitsPerChannel;
    long long _packetType;
    unsigned long long _timestamp;
    NSData *_audioData;
}

@property(retain, nonatomic) NSData *audioData; // @synthesize audioData=_audioData;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) long long packetType; // @synthesize packetType=_packetType;
@property(nonatomic) long long bitsPerChannel; // @synthesize bitsPerChannel=_bitsPerChannel;
@property(nonatomic) long long channelsPerSample; // @synthesize channelsPerSample=_channelsPerSample;
@property(nonatomic) long long sampleRate; // @synthesize sampleRate=_sampleRate;
- (void).cxx_destruct;
- (id)init;

@end

