//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface TXSNALPacket : NSObject
{
    int _nalType;
    unsigned int _codecId;
    NSData *_nalData;
    unsigned long long _gopIndex;
    unsigned long long _gopFrameIndex;
    unsigned long long _frameIndex;
    unsigned long long _refFrameIndex;
    unsigned long long _pts;
    unsigned long long _dts;
}

@property(nonatomic) unsigned int codecId; // @synthesize codecId=_codecId;
@property(nonatomic) unsigned long long dts; // @synthesize dts=_dts;
@property(nonatomic) unsigned long long pts; // @synthesize pts=_pts;
@property(nonatomic) unsigned long long refFrameIndex; // @synthesize refFrameIndex=_refFrameIndex;
@property(nonatomic) unsigned long long frameIndex; // @synthesize frameIndex=_frameIndex;
@property(nonatomic) unsigned long long gopFrameIndex; // @synthesize gopFrameIndex=_gopFrameIndex;
@property(nonatomic) unsigned long long gopIndex; // @synthesize gopIndex=_gopIndex;
@property(retain, nonatomic) NSData *nalData; // @synthesize nalData=_nalData;
@property(nonatomic) int nalType; // @synthesize nalType=_nalType;
- (void).cxx_destruct;
- (id)init;

@end

