//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface UpdateContactLabelCache : NSObject
{
    NSString *oldLabelName;
    NSString *updateLabelName;
}

@property(retain, nonatomic) NSString *updateLabelName; // @synthesize updateLabelName;
@property(retain, nonatomic) NSString *oldLabelName; // @synthesize oldLabelName;
- (void).cxx_destruct;

@end

