//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBMessageObserverDelegate-Protocol.h"

@class MMTimer, NSDate, NSMutableArray, NSMutableSet;
@protocol UploadStreamVoiceDataMgrDelegate;

@interface UploadStreamVoiceDataMgr : MMObject <PBMessageObserverDelegate>
{
    unsigned int _addTaskCount;
    unsigned int _uploadTaskCount;
    NSDate *m_dtStopRecordTime;
    NSMutableSet *m_setEndFlagList;
    _Bool m_bCheckTransResult;
    _Bool m_bReportEnd;
    unsigned int _currentInputId;
    unsigned int _maxPacketSize;
    id <UploadStreamVoiceDataMgrDelegate> _delegate;
    MMTimer *_checkUploadQueueTimer;
    NSMutableArray *_runningQueue;
    NSMutableArray *_waitingQueue;
    double _uploadInterval;
    NSMutableSet *_processingVoiceIds;
}

@property(retain, nonatomic) NSMutableSet *processingVoiceIds; // @synthesize processingVoiceIds=_processingVoiceIds;
@property(nonatomic) double uploadInterval; // @synthesize uploadInterval=_uploadInterval;
@property(nonatomic) unsigned int maxPacketSize; // @synthesize maxPacketSize=_maxPacketSize;
@property(nonatomic) unsigned int currentInputId; // @synthesize currentInputId=_currentInputId;
@property(retain, nonatomic) NSMutableArray *waitingQueue; // @synthesize waitingQueue=_waitingQueue;
@property(retain, nonatomic) NSMutableArray *runningQueue; // @synthesize runningQueue=_runningQueue;
@property(retain, nonatomic) MMTimer *checkUploadQueueTimer; // @synthesize checkUploadQueueTimer=_checkUploadQueueTimer;
@property(nonatomic) __weak id <UploadStreamVoiceDataMgrDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleVoiceTransResponse:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)RemoveRequestFromRunningQueue:(id)arg1;
- (_Bool)doUpload:(id)arg1;
- (void)tryAddNewUploadTask;
- (void)stopUploadTaskWithErr:(int)arg1;
- (void)checkUploadQueue;
- (void)addVoiceIdToProcessingQueue:(id)arg1;
- (void)stopUploadTask;
- (void)clearTempFile;
- (void)safeStopUploadTimer;
- (void)resetUploadTimer;
- (void)StopRecord;
- (void)ClearLastUploadData;
- (void)AddNewPart:(id)arg1;
- (void)Stop;
- (void)Start:(unsigned int)arg1;
- (void)dealloc;
- (id)init;

@end

