//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol UploadAttachmentDataDelegate <NSObject>
- (void)OnUploadAttachmentData:(NSString *)arg1 attachID:(NSString *)arg2 uploadedDataSize:(unsigned int)arg3 err:(int)arg4;
@end

