//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface VoiceExtendCode : NSObject
{
}

+ (void)decodeVoiceField:(struct XmlReaderNode_t *)arg1 UploadVoice:(id)arg2;
+ (void)codeVoiceField:(struct CFastStr *)arg1 UploadVoice:(id)arg2;
+ (_Bool)decodeExtentField:(id)arg1 UploadVoice:(id)arg2;
+ (id)codeExtentField:(id)arg1;

@end

