//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WACameraOperateUtility : NSObject
{
}

+ (id)imageFromImage:(id)arg1 inRect:(struct CGRect)arg2;
+ (id)imageWithImage:(id)arg1 scaledToSize:(struct CGSize)arg2;
+ (id)thumbForVideoWithPath:(id)arg1;
+ (id)getCaptureSessionPreset;
+ (struct CGSize)getCaptureResolution;

@end

