//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

@class PhotoViewController;

@interface WAJSEventHandler_previewImage : WAJSEventHandler_BaseEvent
{
    PhotoViewController *m_photoViewController;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)showImageWithUrls:(id)arg1 current:(id)arg2;
- (void)uninitImageViewer;
- (void)handleJSEvent:(id)arg1;

@end

