//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WAMapView;

@protocol WAMapViewDelegate <NSObject>

@optional
- (void)onMapCalloutClick:(WAMapView *)arg1 data:(NSString *)arg2;
- (void)onMapTap:(WAMapView *)arg1;
- (void)onRegionDidChange:(WAMapView *)arg1;
- (void)onRegionWillChange:(WAMapView *)arg1;
- (void)onControlClick:(WAMapView *)arg1 data:(NSString *)arg2;
- (void)onMarkerClick:(WAMapView *)arg1 data:(NSString *)arg2;
@end

