//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WAMsgNodePermissionInfo;

@protocol WAMsgNodeLaunchLogicDelegate <NSObject>

@optional
- (void)onGetReleaseDownloadUrlFinish:(NSString *)arg1 url:(NSString *)arg2 checksum:(NSString *)arg3 version:(unsigned long long)arg4 errCode:(int)arg5 scene:(unsigned int)arg6;
- (void)onGetDemoDownloadUrlFinish:(NSString *)arg1 url:(NSString *)arg2 checksum:(NSString *)arg3 errCode:(int)arg4 scene:(unsigned int)arg5;
- (void)onGetDebugDownloadUrlFinish:(NSString *)arg1 url:(NSString *)arg2 checksum:(NSString *)arg3 errCode:(int)arg4 scene:(unsigned int)arg5;
- (void)onLaunchAppId:(NSString *)arg1 debugMode:(unsigned int)arg2 reqVersion:(unsigned long long)arg3 permissonInfo:(WAMsgNodePermissionInfo *)arg4 latestVersion:(unsigned long long)arg5 latestChecksum:(NSString *)arg6 errCode:(int)arg7 scene:(unsigned int)arg8;
@end

