//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, WCAddressBaseAddress;

@interface WCAddressControlData : NSObject
{
    WCAddressBaseAddress *structSelectBaseAddress;
    WCAddressBaseAddress *structEditBaseAddress;
    NSArray *m_arrAllAddress;
    NSArray *m_arrAddressStageData;
}

+ (id)getSelectAddressDicFromAddress:(id)arg1;
@property(retain, nonatomic) NSArray *m_arrAddressStageData; // @synthesize m_arrAddressStageData;
@property(retain, nonatomic) NSArray *m_arrAllAddress; // @synthesize m_arrAllAddress;
@property(retain, nonatomic) WCAddressBaseAddress *structEditBaseAddress; // @synthesize structEditBaseAddress;
@property(retain, nonatomic) WCAddressBaseAddress *structSelectBaseAddress; // @synthesize structSelectBaseAddress;
- (void).cxx_destruct;
- (void)dealloc;

@end

