//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSDateFormatter, NSMutableArray, NSString, NSTimer, UIButton, UIImageView, UILabel, UIPageControl, UIScrollView, UITableView, UIView;

@interface WCAddWatchcontactsGuideViewController : MMUIViewController <UIScrollViewDelegate, UITableViewDataSource, UITableViewDelegate>
{
    UIButton *leftNavButton;
    UIButton *rightNavButton;
    UIPageControl *_pageControl;
    NSMutableArray *_recommendConstancts;
    NSMutableArray *_selectedConstanctsArr;
    UITableView *_contactsTable;
    UIScrollView *_scrollView;
    NSMutableArray *_checkImageArr;
    UIView *_progressLine;
    UILabel *_timeLabel;
    UIImageView *_watch;
    NSDateFormatter *_dateformatter;
    NSTimer *_tickTimer;
}

- (void).cxx_destruct;
- (void)selectcontact:(id)arg1;
- (void)skipAddcontacts;
- (void)addcontactsComplete;
- (void)handleTimer;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)stopTimer;
- (void)startAnimation;
- (void)setAvatarInScrollView:(id)arg1 withAvatarArr:(id)arg2;
- (void)setNavigationbar;
- (void)initUI;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

