//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIPopoverPresentationControllerDelegate-Protocol.h"

@class NSString, UIPickerView, UIPopoverController, UIView, UIViewController;
@protocol WCBizPickerViewDelegate;

@interface WCBizPickerView : NSObject <UIPopoverPresentationControllerDelegate>
{
    UIPickerView *m_pickerView;
    id <WCBizPickerViewDelegate> _m_delegate;
    UIView *_contentView;
    UIView *_transparentView;
    UIViewController *_contentVC;
    UIPopoverController *_popoverController;
    long long _lastOri;
}

+ (struct CGSize)getPickerViewSize;
@property(nonatomic) long long lastOri; // @synthesize lastOri=_lastOri;
@property(retain, nonatomic) UIPopoverController *popoverController; // @synthesize popoverController=_popoverController;
@property(retain, nonatomic) UIViewController *contentVC; // @synthesize contentVC=_contentVC;
@property(retain, nonatomic) UIView *transparentView; // @synthesize transparentView=_transparentView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <WCBizPickerViewDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void).cxx_destruct;
- (void)dismissWithAnimated:(_Bool)arg1;
- (void)handleTap:(id)arg1;
- (void)reloadComponent:(long long)arg1;
- (void)setSelectedRow:(long long)arg1 Component:(long long)arg2;
- (void)UIPickerViewDidFinish;
- (void)UIPickerViewDidCancel;
- (long long)adaptivePresentationStyleForPresentationController:(id)arg1;
- (void)showInView:(id)arg1;
- (void)didRotate:(id)arg1;
- (void)dealloc;
- (void)removeAllPickerViewDelegate;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

