//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

@class MMTableViewInfo;

@interface WCDeviceDebugSettingViewController : MMUIViewController
{
    MMTableViewInfo *m_tableViewInfo;
}

- (void).cxx_destruct;
- (void)makeSwitchCell:(id)arg1 CellInfo:(id)arg2;
- (void)onSwitch:(id)arg1;
- (void)viewDidLoad;

@end

