//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ICdnComMgrExt-Protocol.h"

@class CdnSnsTaskInfo, NSMutableArray, NSString;

@interface WCDownloadImageCdnMgr : NSObject <ICdnComMgrExt>
{
    CdnSnsTaskInfo *_curTaskInfo;
    NSMutableArray *_arrDownloadTask;
}

- (void).cxx_destruct;
- (void)OnCdnDownload:(id)arg1;
- (void)OnCdnDownloadProgress:(id)arg1;
- (id)getDataUrl:(id)arg1;
- (_Bool)IsDownloading:(id)arg1 downloadType:(int)arg2;
- (_Bool)isSameDownloadTask:(id)arg1 MediaItem:(id)arg2 downloadType:(int)arg3;
- (void)CheckQueue;
- (void)StopDownloadImage:(id)arg1 downloadType:(int)arg2;
- (void)StartDownloadImage:(id)arg1 downloadType:(int)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

