//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "IWCBusinessJumpExt-Protocol.h"
#import "MMService-Protocol.h"

@class NSString;

@interface WCGameJumpHelper : MMService <MMService, IWCBusinessJumpExt>
{
}

- (void)processTranslateResultWithPath:(id)arg1 queryDict:(id)arg2 parentController:(id)arg3 originUrl:(id)arg4 translateInfo:(id)arg5 jumpController:(id)arg6;
- (void)onServiceTerminate;
- (void)onServiceInit;
- (id)createGameLibraryController:(int)arg1;
- (id)createGameDetailControllerWithAppID:(id)arg1 name:(id)arg2 iconURLString:(id)arg3 brief:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

