//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMUILabel, UIImageView;

@interface WCLabsSettingHeaderView : UIView
{
    MMUILabel *_titleLabel;
    MMUILabel *_descLabel;
    UIImageView *_leftBGIcon;
    UIImageView *_rightBGIcon;
    UIImageView *_labsIcon;
}

+ (double)height;
- (void).cxx_destruct;
- (void)initDescLabel;
- (void)initTitleLabel;
- (void)initLabsIcon;
- (void)initBackground;
- (double)getTitleFontSize;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

