//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCLanDeviceInfo : NSObject
{
    NSString *m_deviceType;
    NSString *m_deviceId;
    NSString *m_manufacturerData;
}

@property(retain, nonatomic) NSString *m_manufacturerData; // @synthesize m_manufacturerData;
@property(retain, nonatomic) NSString *m_deviceId; // @synthesize m_deviceId;
@property(retain, nonatomic) NSString *m_deviceType; // @synthesize m_deviceType;
- (void).cxx_destruct;

@end

