//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "BaseEmoticonViewDelegate-Protocol.h"
#import "ContactsSelectorControllerDelegate-Protocol.h"
#import "FacebookViewControllerDelegate-Protocol.h"
#import "IFacebookAuthExt-Protocol.h"
#import "IMMAssetICloudExt-Protocol.h"
#import "IMMFacebookMgrExt-Protocol.h"
#import "IMMGrowTextViewExt-Protocol.h"
#import "IMsgExt-Protocol.h"
#import "InputControllerDelegate-Protocol.h"
#import "MMTableViewInfoDelegate-Protocol.h"
#import "MMTwitterAuthExt-Protocol.h"
#import "SelectorControllerDelegate-Protocol.h"
#import "SightViewDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"
#import "WCDragableSelectorViewDelegate-Protocol.h"
#import "WCFacadeExt-Protocol.h"
#import "WCGroupTagViewControllerDelegate-Protocol.h"
#import "WCTimelinePOIPickerViewControllerDelegate-Protocol.h"
#import "scrollViewDelegate-Protocol.h"

@class CLLocation, ContactsSelectorController, EmoticonBoardView, ImageSelectorController, MMAsset, MMGrowTextView, MMLoadingView, MMTableViewInfo, MMTimer, NSArray, NSMutableArray, NSString, SightDraft, SightIconView, SightView, UIActivityIndicatorView, UIButton, UIImage, UIImageView, UIView, WCDataItem, WCDragDeleteBarView, WCDragTipView, WCHeadViewCellInfo, WCInputController, WCLocationInfo, WCMusicInfo, WCPOIStarView, WCSelectorView, WCTimelinePOIPickerViewController;
@protocol WCCommitViewAnimationDelegate;

@interface WCNewCommitViewController : MMUIViewController <InputControllerDelegate, BaseEmoticonViewDelegate, IMMAssetICloudExt, WCGroupTagViewControllerDelegate, SightViewDelegate, FacebookViewControllerDelegate, WCDragableSelectorViewDelegate, UIScrollViewDelegate, scrollViewDelegate, UITextViewDelegate, SelectorControllerDelegate, MMTableViewInfoDelegate, ContactsSelectorControllerDelegate, UIAlertViewDelegate, IMsgExt, WCFacadeExt, MMTwitterAuthExt, IMMFacebookMgrExt, IFacebookAuthExt, IMMGrowTextViewExt, WCTimelinePOIPickerViewControllerDelegate>
{
    MMTableViewInfo *_tableViewInfo;
    MMGrowTextView *_textView;
    UIView *_headView;
    WCSelectorView *_withImageView;
    WCSelectorView *_withContactView;
    UIButton *_qzoneButton;
    UIButton *_facebookButton;
    UIButton *_twitterButton;
    UIImage *_sightThumbImage;
    UIImageView *_sightThumbImageView;
    UIActivityIndicatorView *_sightLoadingView;
    SightIconView *_progressView;
    ImageSelectorController *_imageSelectorController;
    ContactsSelectorController *_contactsSelectorController;
    WCInputController *_inputController;
    _Bool _bHasInput;
    UIImageView *_inputView;
    UIButton *_expressionButton;
    unsigned int _iInputSection;
    id <WCCommitViewAnimationDelegate> _delegate;
    WCDataItem *_cacheDateItem;
    MMLoadingView *_loadingView;
    MMTimer *_fireTimer;
    WCLocationInfo *_poiInfo;
    WCMusicInfo *_musicInfo;
    _Bool _bNeedRefresh;
    _Bool _bNeedAnimation;
    _Bool _bShowLocation;
    _Bool _bHideAddView;
    unsigned long long _singlePasteTextMaxLength;
    WCTimelinePOIPickerViewController *_poiPickerViewController;
    NSString *_loadingOKStr;
    _Bool m_hasClickDone;
    WCDragTipView *_dragTipView;
    WCHeadViewCellInfo *_headCell;
    _Bool m_isUseMMAsset;
    _Bool m_hasConfirmReturn;
    _Bool m_hasICloudImage;
    _Bool m_bFromWCList;
    _Bool _hasShowDragTip;
    EmoticonBoardView *m_emoticonBoardView;
    CLLocation *m_imageLocation;
    unsigned long long _type;
    SightDraft *_sightDraft;
    MMAsset *_sightAsset;
    NSArray *_tempSelectContacts;
    NSMutableArray *_m_imageLocationAry;
    SightView *_m_sightFullScreenPreviewView;
    WCDragDeleteBarView *_deleteBarView;
    WCPOIStarView *_poiStarView;
}

@property(retain, nonatomic) WCPOIStarView *poiStarView; // @synthesize poiStarView=_poiStarView;
@property(nonatomic) _Bool hasShowDragTip; // @synthesize hasShowDragTip=_hasShowDragTip;
@property(retain, nonatomic) WCDragDeleteBarView *deleteBarView; // @synthesize deleteBarView=_deleteBarView;
@property(retain, nonatomic) SightView *m_sightFullScreenPreviewView; // @synthesize m_sightFullScreenPreviewView=_m_sightFullScreenPreviewView;
@property(retain, nonatomic) NSMutableArray *m_imageLocationAry; // @synthesize m_imageLocationAry=_m_imageLocationAry;
@property(retain, nonatomic) NSArray *tempSelectContacts; // @synthesize tempSelectContacts=_tempSelectContacts;
@property(retain, nonatomic) MMAsset *sightAsset; // @synthesize sightAsset=_sightAsset;
@property(retain, nonatomic) SightDraft *sightDraft; // @synthesize sightDraft=_sightDraft;
@property(nonatomic) _Bool bHideAddView; // @synthesize bHideAddView=_bHideAddView;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) _Bool m_bFromWCList; // @synthesize m_bFromWCList;
@property(retain, nonatomic) CLLocation *m_imageLocation; // @synthesize m_imageLocation;
@property(nonatomic) _Bool m_hasICloudImage; // @synthesize m_hasICloudImage;
@property(nonatomic) _Bool m_hasConfirmReturn; // @synthesize m_hasConfirmReturn;
@property(retain, nonatomic) EmoticonBoardView *m_emoticonBoardView; // @synthesize m_emoticonBoardView;
@property(nonatomic) _Bool m_isUseMMAsset; // @synthesize m_isUseMMAsset;
@property(retain, nonatomic) NSString *loadingOKStr; // @synthesize loadingOKStr=_loadingOKStr;
@property(retain, nonatomic) WCMusicInfo *musicInfo; // @synthesize musicInfo=_musicInfo;
@property(retain, nonatomic) WCLocationInfo *poiInfo; // @synthesize poiInfo=_poiInfo;
@property(nonatomic) _Bool bShowLocation; // @synthesize bShowLocation=_bShowLocation;
@property(nonatomic) _Bool bNeedAnimation; // @synthesize bNeedAnimation=_bNeedAnimation;
@property(nonatomic) __weak id <WCCommitViewAnimationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)onPOIPickerFinished:(id)arg1;
- (_Bool)couldSelectContacts;
- (void)hideInputController;
- (_Bool)showAddView;
- (void)updateSelectorView;
- (_Bool)shouldJustReturnMMAsset;
- (void)imagesUpdated;
- (void)onWCPostPrivacyChanged;
- (void)facebookCheckAccessTokenValidFinished:(_Bool)arg1;
- (void)fbDidNotLogin;
- (void)fbDidLogin;
- (void)twitterCheckAccessTokenValidFinished:(int)arg1;
- (void)twitterAuthFinished:(int)arg1;
- (void)twitterWillStartOpenSafari;
- (void)adjustSubviewRects;
- (void)updateImageLocation:(unsigned int *)arg1;
- (void)processUploadTask:(id)arg1;
- (void)postNewItemForSight;
- (void)OnDone;
- (void)addPoiInfoForTask:(id)arg1;
- (void)OnPostTimeline;
- (_Bool)checkImageState;
- (void)afterProcessSingleImage;
- (_Bool)processImage;
- (void)cancelIcloudActivity;
- (void)doExit;
- (void)OnReturn;
- (void)OnFacebookBinded;
- (void)onTwitterClicked:(id)arg1;
- (void)onFacebookClicked:(id)arg1;
- (void)onLocationCellClicked;
- (void)onWithContactCellClicked;
- (void)onPrivacyCellClicked;
- (void)onQZoneClicked:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)bindFacebook;
- (void)bindQQ;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)showPrivacyAlertView;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)shareOptionsCheck;
- (void)initView;
- (void)reloadType;
- (void)reloadData;
- (id)getShowAddress;
- (void)setDeleteBarHidden:(_Bool)arg1;
- (void)createSubviews;
- (void)saveShareOptions;
- (void)restoreLastShareOptions;
- (_Bool)shouldShowEvaluatePOI;
- (void)makeEvaluatePOICell:(id)arg1 CellInfo:(id)arg2;
- (void)removeOldText;
- (void)writeOldText:(id)arg1;
- (id)openOldText;
- (id)getViewController;
- (id)initWithSightDraft:(id)arg1;
- (id)initWithImages:(id)arg1 contacts:(id)arg2;
- (id)init;
- (void)commonInit;
- (void)onDragableSelectorViewHeightChanged;
- (_Bool)onEndCollectionViewCellMovement:(long long)arg1;
- (void)onCollectionViewCellMoved:(struct CGPoint)arg1;
- (void)reloadExpressionButtonImage:(int)arg1;
- (void)onExpressionButtonClicked:(id)arg1;
- (void)keyboardDidHide;
- (void)textViewTextDidChange;
- (void)keyboardWillShow;
- (void)MMGrowTextViewBeginEditing:(id)arg1;
- (void)MMGrowTextViewHeightDidChanged:(id)arg1;
- (void)didCommitText:(id)arg1;
- (void)resignInput;
- (void)becomeInput;
- (void)updateContentOffset;
- (void)initInputController;
- (void)initEmoticonView;
- (void)initInputToolView;
- (void)scrollViewDidScroll:(id)arg1;
- (void)touchesBegan_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)GroupTagViewSelectTempContacts:(id)arg1;
- (void)onAssetImageDonwloadProgress:(double)arg1 assetUrl:(id)arg2;
- (void)onAssetImageDonwloadStart:(id)arg1;
- (void)onTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)beginAnimationStepTwoWithCustomView:(id)arg1;
- (void)beginAnimationStepTwo;
- (void)beginAnimationStepOne;
- (void)onLoadingShowOK:(id)arg1;
- (void)showLoadingView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

