//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSMutableArray, NSString, UIColor, UITextField;
@protocol WCPayInputViewDelegate;

@interface WCPayInputView : UIView <UITextFieldDelegate>
{
    id <WCPayInputViewDelegate> _delegate;
    long long _inputCount;
    UIColor *_fontColor;
    long long _fontSize;
    long long _rectangleMargin;
    unsigned long long _borders;
    double _borderWidth;
    UIColor *_borderColor;
    UITextField *_textField;
    NSMutableArray *_labels;
    struct CGSize _rectangleSize;
}

@property(retain, nonatomic) NSMutableArray *labels; // @synthesize labels=_labels;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(nonatomic) unsigned long long borders; // @synthesize borders=_borders;
@property(nonatomic) long long rectangleMargin; // @synthesize rectangleMargin=_rectangleMargin;
@property(nonatomic) struct CGSize rectangleSize; // @synthesize rectangleSize=_rectangleSize;
@property(nonatomic) long long fontSize; // @synthesize fontSize=_fontSize;
@property(nonatomic) UIColor *fontColor; // @synthesize fontColor=_fontColor;
@property(nonatomic) long long inputCount; // @synthesize inputCount=_inputCount;
@property(nonatomic) __weak id <WCPayInputViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidChange:(id)arg1;
- (void)layout;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

