//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString, WCPayBeforePayInfo, WCPayEntrustPayInfo, WCPayTradeFavInfo;

@interface WCPayMultiOrderDetail : NSObject
{
    unsigned int m_productNum;
    long long m_totalFee;
    NSArray *m_supportBankArray;
    NSMutableArray *m_orderDetailArray;
    _Bool m_isOpenProtocal;
    _Bool m_bNeedBindCardToShowFavInfo;
    NSString *m_nsDiscountWording;
    NSString *m_nsFavorRuleWording;
    WCPayTradeFavInfo *m_oWCPayTradeFavInfo;
    unsigned long long m_assignUserInfoPay;
    NSString *m_nsJumpToSafariUrl;
    WCPayEntrustPayInfo *m_entrustPayInfo;
    _Bool _m_isSupportBindCard;
    _Bool _m_isSupportRetry;
    _Bool _bIsUseNewPaidSuccPage;
    NSString *m_assignedUserName;
    NSString *m_assignUserCreId;
    long long m_assignUserCreType;
    NSString *m_assignPayInfo;
    NSString *m_payFlag;
    NSString *_paySuccBtnWording;
    WCPayBeforePayInfo *_m_beforePayInfo;
}

@property(retain, nonatomic) WCPayBeforePayInfo *m_beforePayInfo; // @synthesize m_beforePayInfo=_m_beforePayInfo;
@property(nonatomic) _Bool bIsUseNewPaidSuccPage; // @synthesize bIsUseNewPaidSuccPage=_bIsUseNewPaidSuccPage;
@property(retain, nonatomic) NSString *paySuccBtnWording; // @synthesize paySuccBtnWording=_paySuccBtnWording;
@property(nonatomic) _Bool m_isSupportRetry; // @synthesize m_isSupportRetry=_m_isSupportRetry;
@property(nonatomic) _Bool m_isSupportBindCard; // @synthesize m_isSupportBindCard=_m_isSupportBindCard;
@property(retain, nonatomic) WCPayEntrustPayInfo *m_entrustPayInfo; // @synthesize m_entrustPayInfo;
@property(retain, nonatomic) NSString *m_nsFavorRuleWording; // @synthesize m_nsFavorRuleWording;
@property(retain, nonatomic) NSString *m_nsDiscountWording; // @synthesize m_nsDiscountWording;
@property(retain, nonatomic) NSString *m_payFlag; // @synthesize m_payFlag;
@property(retain, nonatomic) NSString *m_nsJumpToSafariUrl; // @synthesize m_nsJumpToSafariUrl;
@property(retain, nonatomic) NSString *m_assignPayInfo; // @synthesize m_assignPayInfo;
@property(nonatomic) long long m_assignUserCreType; // @synthesize m_assignUserCreType;
@property(retain, nonatomic) NSString *m_assignUserCreId; // @synthesize m_assignUserCreId;
@property(retain, nonatomic) NSString *m_assignedUserName; // @synthesize m_assignedUserName;
@property(nonatomic) unsigned long long m_assignUserInfoPay; // @synthesize m_assignUserInfoPay;
@property(nonatomic) _Bool m_bNeedBindCardToShowFavInfo; // @synthesize m_bNeedBindCardToShowFavInfo;
@property(retain, nonatomic) WCPayTradeFavInfo *m_oWCPayTradeFavInfo; // @synthesize m_oWCPayTradeFavInfo;
@property(nonatomic) _Bool m_isOpenProtocal; // @synthesize m_isOpenProtocal;
@property(retain, nonatomic) NSMutableArray *m_orderDetailArray; // @synthesize m_orderDetailArray;
@property(retain, nonatomic) NSArray *m_supportBankArray; // @synthesize m_supportBankArray;
@property(nonatomic) long long m_totalFee; // @synthesize m_totalFee;
@property(nonatomic) unsigned int m_productNum; // @synthesize m_productNum;
- (void).cxx_destruct;
- (void)dealloc;

@end

