//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

@class UIButton, WCBaseKeyboardToolBar, WCBaseTextFieldItem, WCPayTenpaySecureCtrlItem;
@protocol WCPayCreditPayFillPartIdentifierInfoViewControllerDelegate;

@interface WCPayCreditPayFillPartIdentifierInfoViewController : WCPayBaseViewController
{
    UIButton *m_footerButton;
    WCBaseKeyboardToolBar *m_keyboardBar;
    WCBaseTextFieldItem *m_nameTextFieldItem;
    WCPayTenpaySecureCtrlItem *m_idNumberTextFieldItem;
    id <WCPayCreditPayFillPartIdentifierInfoViewControllerDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)WCBaseInfoItemPressReturnKey:(id)arg1;
- (void)onNext;
- (void)setDelegate:(id)arg1;
- (void)viewDidLoad;
- (void)makeIDNumberInfoCell:(id)arg1;
- (void)makeNameInfoCell:(id)arg1;
- (void)initNavigationBar;
- (void)initTextFieldItem;
- (void)initFooterView;
- (void)reloadTableView;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)dealloc;
- (id)init;

@end

