//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CommonMessageViewModel.h"

@class NSMutableArray, NSString, UIFont;

@interface WCPayC2CAAUnPayNotifyViewModel : CommonMessageViewModel
{
    NSMutableArray *_contentTextStyles;
    double _translatedLineY;
    double _contentMidY;
    NSString *_contentText;
    UIFont *_contentTextFont;
    double _labelWidth;
    long long _parserType;
    struct CGSize _contentTextSize;
}

+ (_Bool)canCreateMessageViewModelWithMessageWrap:(id)arg1;
@property(nonatomic) struct CGSize contentTextSize; // @synthesize contentTextSize=_contentTextSize;
@property(nonatomic) long long parserType; // @synthesize parserType=_parserType;
@property(nonatomic) double labelWidth; // @synthesize labelWidth=_labelWidth;
@property(retain, nonatomic) UIFont *contentTextFont; // @synthesize contentTextFont=_contentTextFont;
@property(retain, nonatomic) NSString *contentText; // @synthesize contentText=_contentText;
@property(nonatomic) double contentMidY; // @synthesize contentMidY=_contentMidY;
@property(nonatomic) double translatedLineY; // @synthesize translatedLineY=_translatedLineY;
@property(retain, nonatomic) NSMutableArray *contentTextStyles; // @synthesize contentTextStyles=_contentTextStyles;
- (void).cxx_destruct;
- (void)setLinkHighlighted:(_Bool)arg1 url:(id)arg2;
- (id)translateInfo;
- (_Bool)canShowTranslatedText;
- (_Bool)canShowTranslateView;
- (_Bool)canShowTranslateBottomView;
- (_Bool)isShowSourceView;
- (struct CGSize)calculateContentTextSize;
- (struct CGSize)measureContentViewSize:(struct CGSize)arg1;
- (id)cellViewClassName;

@end

