//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCPayWXBorrowMoneyItem : NSObject
{
    int m_enWCPayWXBorrowMoneyItemStatus;
    NSString *m_nsToOpenTitle;
    NSString *m_nsRedirectUrl;
    NSString *m_nsBankType;
    NSString *m_nsBankName;
    NSString *m_nsBankLogoUrl;
    NSString *m_nsBankBgUrl;
    NSString *m_nsBankMasterUrl;
    NSString *m_nsIsOverDue;
    NSString *m_nsAvailableOtb;
    unsigned int m_uiRedCodIndex;
}

@property(nonatomic) unsigned int m_uiRedCodIndex; // @synthesize m_uiRedCodIndex;
@property(retain, nonatomic) NSString *m_nsBankMasterUrl; // @synthesize m_nsBankMasterUrl;
@property(retain, nonatomic) NSString *m_nsBankBgUrl; // @synthesize m_nsBankBgUrl;
@property(retain, nonatomic) NSString *m_nsToOpenTitle; // @synthesize m_nsToOpenTitle;
@property(retain, nonatomic) NSString *m_nsRedirectUrl; // @synthesize m_nsRedirectUrl;
@property(retain, nonatomic) NSString *m_nsIsOverDue; // @synthesize m_nsIsOverDue;
@property(retain, nonatomic) NSString *m_nsBankType; // @synthesize m_nsBankType;
@property(retain, nonatomic) NSString *m_nsBankName; // @synthesize m_nsBankName;
@property(retain, nonatomic) NSString *m_nsBankLogoUrl; // @synthesize m_nsBankLogoUrl;
@property(retain, nonatomic) NSString *m_nsAvailableOtb; // @synthesize m_nsAvailableOtb;
@property(nonatomic) int m_enWCPayWXBorrowMoneyItemStatus; // @synthesize m_enWCPayWXBorrowMoneyItemStatus;
- (void).cxx_destruct;

@end

