//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCBaseControlMgrExt-Protocol.h"
#import "WCPayPayMoneyLogicDelegate-Protocol.h"

@class NSString, WCPayInnerPayRequestStruct, WCPayPayMoneyLogic;

@interface WCPayMoneyFromInnerPayLogic : WCPayControlLogic <WCBaseControlMgrExt, WCPayPayMoneyLogicDelegate>
{
    WCPayPayMoneyLogic *m_payLogic;
    WCPayInnerPayRequestStruct *m_oWCPayInnerPayRequestStruct;
    NSString *m_dicExtraInfo;
    NSString *m_nsRequestKey;
    unsigned int m_eSene;
}

- (void).cxx_destruct;
- (void)OnGetGenPaypreErrorRequest:(id)arg1 ErrorMsg:(id)arg2;
- (void)OnGetGenPaypreRequest:(id)arg1 SessionID:(id)arg2 AppSource:(id)arg3;
- (void)onWCBaseLogicDidStop:(unsigned int)arg1;
- (_Bool)gotoViewController:(id)arg1;
- (id)getInnerPayResponseStruct;
- (void)stopLogic;
- (void)startLogic;
- (void)dealloc;
- (id)initWithInnerPayRequest:(id)arg1 extraInfo:(id)arg2;
- (id)initWithInnerPayParam:(id)arg1;
- (id)initWithInnerPayRequest:(id)arg1 Scene:(int)arg2;
- (id)initWithInnerPayRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

