//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class WCDataItem;

@interface WCPattern : NSObject <NSCoding>
{
    WCDataItem *dataItem;
    double lastAccessTime;
}

@property(nonatomic) double lastAccessTime; // @synthesize lastAccessTime;
@property(retain, nonatomic) WCDataItem *dataItem; // @synthesize dataItem;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

