//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AsyncBizSubscribeRequest, AsyncBizSubscribeResponse, FestivalHongBaoReq, FestivalHongBaoRes, HongBaoReq, HongBaoRes;

@protocol WCRedEnvelopesNetworkHelperDelegate <NSObject>
- (void)OnWCToAsyncBizSubscribeResponse:(AsyncBizSubscribeResponse *)arg1 Request:(AsyncBizSubscribeRequest *)arg2;
- (void)OnWCToBizHBCommonErrorResponse:(HongBaoRes *)arg1 Request:(HongBaoReq *)arg2;
- (void)OnWCToBizHBCommonSystemErrorResponse:(HongBaoRes *)arg1 Request:(HongBaoReq *)arg2;
- (void)OnWCToBizHBCommonResponse:(HongBaoRes *)arg1 Request:(HongBaoReq *)arg2;
- (void)OnWCToEnterpriseHBCommonErrorResponse:(FestivalHongBaoRes *)arg1 Request:(FestivalHongBaoReq *)arg2;
- (void)OnWCToEnterpriseHBCommonSystemErrorResponse:(FestivalHongBaoRes *)arg1 Request:(FestivalHongBaoReq *)arg2;
- (void)OnWCToEnterpriseHBCommonResponse:(FestivalHongBaoRes *)arg1 Request:(FestivalHongBaoReq *)arg2;
- (void)OnWCToHongbaoCommonErrorResponse:(HongBaoRes *)arg1 Request:(HongBaoReq *)arg2;
- (void)OnWCToHongbaoCommonSystemErrorResponse:(HongBaoRes *)arg1 Request:(HongBaoReq *)arg2;
- (void)OnWCToHongbaoCommonResponse:(HongBaoRes *)arg1 Request:(HongBaoReq *)arg2;
@end

