//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CContact, MMTableView, NSString;

@interface WCSetStrangerPermissionsViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate>
{
    MMTableView *_tableView;
    CContact *_contact;
}

- (void).cxx_destruct;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)makeSwitchCell:(id)arg1 tip:(id)arg2 status:(_Bool)arg3 tag:(long long)arg4;
- (void)onSwitchValueChange:(id)arg1;
- (void)viewDidLoad;
- (void)initView;
- (void)onDissmiss;
- (void)dealloc;
- (id)initWithUserName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

