//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface WCShareCardLayoutDataItem : MMObject <PBCoding>
{
    NSString *cardTpId;
    NSString *announceMent;
    unsigned int layoutEndTime;
    unsigned int _top;
}

+ (void)initialize;
@property(nonatomic) unsigned int top; // @synthesize top=_top;
@property(nonatomic) unsigned int layoutEndTime; // @synthesize layoutEndTime;
@property(retain, nonatomic) NSString *announceMent; // @synthesize announceMent;
@property(retain, nonatomic) NSString *cardTpId; // @synthesize cardTpId;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

