//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "IContactMgrExt-Protocol.h"
#import "INetworkStatusMgrExt-Protocol.h"
#import "MMKernelExt-Protocol.h"
#import "MMService-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class MemoryMappedKV, NSCharacterSet, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface WCSiriMgr : MMService <MMService, MMKernelExt, PBMessageObserverDelegate, IContactMgrExt, INetworkStatusMgrExt>
{
    NSObject<OS_dispatch_queue> *m_updateContactQueue;
    _Bool _needRefreshSessionKey;
    _Bool _isRefreshingSessionKey;
    _Bool _isSirikitAvaiable;
    _Bool _trySiriRecovery;
    MemoryMappedKV *_mappedKV;
    NSCharacterSet *_symbolCharacterSet;
}

+ (id)getSiriDeviceId;
@property(retain, nonatomic) NSCharacterSet *symbolCharacterSet; // @synthesize symbolCharacterSet=_symbolCharacterSet;
@property(retain, nonatomic) MemoryMappedKV *mappedKV; // @synthesize mappedKV=_mappedKV;
@property(nonatomic) _Bool trySiriRecovery; // @synthesize trySiriRecovery=_trySiriRecovery;
@property(nonatomic) _Bool isSirikitAvaiable; // @synthesize isSirikitAvaiable=_isSirikitAvaiable;
@property(nonatomic) _Bool isRefreshingSessionKey; // @synthesize isRefreshingSessionKey=_isRefreshingSessionKey;
@property(nonatomic) _Bool needRefreshSessionKey; // @synthesize needRefreshSessionKey=_needRefreshSessionKey;
- (void).cxx_destruct;
- (void)updateVocabulary:(id)arg1;
- (void)onModifyContact:(id)arg1;
- (void)onDeleteContact:(id)arg1;
- (id)getSiriContactBy:(id)arg1 inDict:(id)arg2;
- (void)onNewContact:(id)arg1;
- (void)confirmAlive;
- (void)onContactListUpdate:(unsigned int)arg1;
- (id)vocabularyFromContactName:(id)arg1;
- (_Bool)IsEnChar:(unsigned short)arg1;
- (void)addVocabularyFor:(id)arg1 toVocabularys:(id)arg2;
- (id)convertContactToSiriIfNeed:(id)arg1;
- (void)portContactsDataToContainerFolderWithSession:(id)arg1;
- (void)updateApplicationContextIfCould;
- (void)checkAndRefreshSessionKeyIfNeed;
- (_Bool)isSessionKeyCached;
- (void)handleGetIosExtensionKeyResp:(id)arg1 Event:(unsigned int)arg2;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)getExtensionKeyForceRefresh;
- (void)onAuthOK;
- (void)onNetworkStatusChange:(unsigned int)arg1;
- (id)getQueue;
- (_Bool)isSiriRestricted;
- (_Bool)isSiriKitAvailable;
- (void)dealloc;
- (void)onPreQuit;
- (void)onServiceEnterForeground;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

