//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBCoding-Protocol.h"

@class NSString, WCSnsOperation;

@interface WCSnsLocalCacheData : MMObject <PBCoding>
{
    unsigned int updateTime;
    WCSnsOperation *snsOperation;
    NSString *itemId;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *itemId; // @synthesize itemId;
@property(retain, nonatomic) WCSnsOperation *snsOperation; // @synthesize snsOperation;
@property(nonatomic) unsigned int updateTime; // @synthesize updateTime;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

