//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WNParagraphParser : NSObject
{
}

- (id)formatHtml:(id)arg1;
- (void)mergeTextParaInfoArray:(id)arg1;
- (_Bool)hasKeyTagChilden:(struct XmlReaderNode_t *)arg1;
- (id)parseAttrTextFromHtmlNode:(struct XmlReaderNode_t *)arg1;
- (id)parseFromTodoElement:(struct XmlReaderNode_t *)arg1;
- (id)parseFromListElement:(struct XmlReaderNode_t *)arg1 ListDataType:(int)arg2;
- (id)parseFromHrElement:(struct XmlReaderNode_t *)arg1;
- (id)parseFromObjectElement:(struct XmlReaderNode_t *)arg1;
- (void)parseXmlNode:(struct XmlReaderNode_t *)arg1 toArray:(id)arg2;
- (id)convertHtmlFromAttibutedString:(id)arg1;
- (_Bool)parse:(id)arg1 toArray:(id)arg2;

@end

