//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WNTextCutter : NSObject
{
}

+ (int)GetMaxArticleLength;
+ (int)GetMaxParagraphLength;
+ (id)cutTextParagraphByLenth:(id)arg1;
+ (id)cutTextParagraph:(id)arg1;
+ (id)cutTextParagraphWithUIKit:(id)arg1;
+ (_Bool)needCutLongText:(id)arg1;
+ (double)getAttrTextHeightByTextKit:(id)arg1;
+ (id)cutTextParagraphV2:(id)arg1;

@end

